In [2]:
import numpy as np # 배열,연산 제공 라이브러리
import pandas as pd # 테이블 형식 데이터 제공 라이브러리

In [3]:
data = pd.read_csv("music_rare.csv")

C:\Users\CGI\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
data = data.iloc[:,:5]

In [5]:
data

,name,tag,title,singer,image
0,선베드에 누워서 파도소리와 함께,"해외,여름,휴양지/해변,바다,쉬는시간,여유로운,주말/휴일,나른해지는",Tú,Maye,https://image.bugsm.co.kr/album/images/50/1485...
1,선베드에 누워서 파도소리와 함께,"해외,여름,휴양지/해변,바다,쉬는시간,여유로운,주말/휴일,나른해지는",Piel Canela,Cuco,https://image.bugsm.co.kr/album/images/50/1466...
2,선베드에 누워서 파도소리와 함께,"해외,여름,휴양지/해변,바다,쉬는시간,여유로운,주말/휴일,나른해지는",ily (i love you baby) (feat. Emilee),Surf Mesa,https://image.bugsm.co.kr/album/images/50/1393...
3,선베드에 누워서 파도소리와 함께,"해외,여름,휴양지/해변,바다,쉬는시간,여유로운,주말/휴일,나른해지는","Honey, There’s the Door",Haley Reinhart(할리 라인하르트),https://image.bugsm.co.kr/album/images/50/2026...
4,선베드에 누워서 파도소리와 함께,"해외,여름,휴양지/해변,바다,쉬는시간,여유로운,주말/휴일,나른해지는",Sea Salt,Quadron(쿼드론),https://image.bugsm.co.kr/album/images/50/3720...
...,...,...,...,...,...
125164,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"위아이,컴백,기분전환,감성",TWILIGHT,위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
125165,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"위아이,컴백,기분전환,감성",DOREMIFA,위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
125166,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"위아이,컴백,기분전환,감성",안고 싶어 (Hug You),위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
125167,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"위아이,컴백,기분전환,감성",꼬리별 (TIMELESS),위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
125168,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"위아이,컴백,기분전환,감성",도화선 (Fuze) (Prod.by 장대현),위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...

In [21]:
# 원하는 컬럼만 선택해서 가져오고 싶을때 
# df[['A','B']]   / df.iloc[:,[0,2]]   / df.drop(['B','D'], axis=1)

df1 = data[['name','title','singer']]

In [150]:
df1

,name,title,singer
0,선베드에 누워서 파도소리와 함께,Tú,Maye
1,선베드에 누워서 파도소리와 함께,Piel Canela,Cuco
2,선베드에 누워서 파도소리와 함께,ily (i love you baby) (feat. Emilee),Surf Mesa
3,선베드에 누워서 파도소리와 함께,"Honey, There’s the Door",Haley Reinhart(할리 라인하르트)
4,선베드에 누워서 파도소리와 함께,Sea Salt,Quadron(쿼드론)
...,...,...,...
125164,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,TWILIGHT,위아이 (WEi)
125165,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,DOREMIFA,위아이 (WEi)
125166,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,안고 싶어 (Hug You),위아이 (WEi)
125167,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,꼬리별 (TIMELESS),위아이 (WEi)
125168,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,도화선 (Fuze) (Prod.by 장대현),위아이 (WEi)

In [37]:
# 중복 확인 
df2 = data[['title','singer']]
df2[df2.duplicated()]

                title                     singer
200                유성                        2단지
314          16 Shots               Stefflon Don
364              눈물바람                     9와 숫자들
410             Happy  Julia Michaels (줄리아 마이클스)
418         New Light          John Mayer(존 메이어)
...               ...                        ...
125152             꿈에                        비투비
125154       Fly Away                        비투비
125155  언젠가 (SOMEDAY)                        비투비
125156       집으로 가는 길                        비투비
125157           괜찮아요                        비투비

[59116 rows x 2 columns]

In [109]:
# 원하는 값 튜플 만들기 
title_list=[]
singer_list=[]

for i in range(len(df2)):
    title_list.append([df2['title'][i]])
    singer_list.append([df2['singer'][i]])

In [101]:
# 데이터 매핑을 위해 비교할 데이터프레임 생성
df3= data[['name']]
df3['song_info']=raw_list
display(df3)

C:\Users\CGI\Anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

,name,song_info
0,선베드에 누워서 파도소리와 함께,"[Tú, Maye]"
1,선베드에 누워서 파도소리와 함께,"[Piel Canela, Cuco]"
2,선베드에 누워서 파도소리와 함께,"[ily (i love you baby) (feat. Emilee), Surf Mesa]"
3,선베드에 누워서 파도소리와 함께,"[Honey, There’s the Door, Haley Reinhart(할리 라인..."
4,선베드에 누워서 파도소리와 함께,"[Sea Salt, Quadron(쿼드론)]"
...,...,...
125164,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"[TWILIGHT, 위아이 (WEi)]"
125165,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"[DOREMIFA, 위아이 (WEi)]"
125166,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"[안고 싶어 (Hug You), 위아이 (WEi)]"
125167,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"[꼬리별 (TIMELESS), 위아이 (WEi)]"
125168,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,"[도화선 (Fuze) (Prod.by 장대현), 위아이 (WEi)]"

In [119]:
song = pd.read_csv("song.csv")

In [145]:
no = song[(song['SONG_NAME']==data["title"][4]) & (song['SINGERS']==data["singer"][4])]['SONG_NO']
no

2    2
Name: SONG_NO, dtype: int64

In [148]:
int_no=int(no)
int_no

2

In [149]:
type(int_no)

int

In [121]:
song

,SONG_NO,SONG_NAME,SINGERS,ALBUM_IMG
0,0,Tú,Maye,https://image.bugsm.co.kr/album/images/50/1485...
1,1,"Honey, There’s the Door",Haley Reinhart(할리 라인하르트),https://image.bugsm.co.kr/album/images/50/2026...
2,2,Sea Salt,Quadron(쿼드론),https://image.bugsm.co.kr/album/images/50/3720...
3,3,Inside Friend (feat. John Mayer),Leon Bridges(리온 브릿지스),https://image.bugsm.co.kr/album/images/50/1409...
4,4,Elegy,Mild High Club,https://image.bugsm.co.kr/album/images/50/5333...
...,...,...,...,...
66048,66048,TWILIGHT,위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
66049,66049,DOREMIFA,위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
66050,66050,안고 싶어 (Hug You),위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
66051,66051,꼬리별 (TIMELESS),위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...
66052,66052,도화선 (Fuze) (Prod.by 장대현),위아이 (WEi),https://cdnimg.melon.co.kr/cm2/album/images/10...

In [154]:
song_num = []
for i in range(len(data)):
    no = song[(song['SONG_NAME']==data["title"][i]) & (song['SINGERS']==data["singer"][i])]['SONG_NO']
    song_num.append(int(no))
df3['song_info']=song_num

C:\Users\CGI\Anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [155]:
df3

,name,title,singer,song_info
0,선베드에 누워서 파도소리와 함께,[Tú],[Maye],0
1,선베드에 누워서 파도소리와 함께,[Piel Canela],[Cuco],21158
2,선베드에 누워서 파도소리와 함께,[ily (i love you baby) (feat. Emilee)],[Surf Mesa],25730
3,선베드에 누워서 파도소리와 함께,"[Honey, There’s the Door]",[Haley Reinhart(할리 라인하르트)],1
4,선베드에 누워서 파도소리와 함께,[Sea Salt],[Quadron(쿼드론)],2
...,...,...,...,...
125164,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,[TWILIGHT],[위아이 (WEi)],66048
125165,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,[DOREMIFA],[위아이 (WEi)],66049
125166,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,[안고 싶어 (Hug You)],[위아이 (WEi)],66050
125167,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,[꼬리별 (TIMELESS)],[위아이 (WEi)],66051
125168,위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용,[도화선 (Fuze) (Prod.by 장대현)],[위아이 (WEi)],66052

In [159]:
relation_df = df3[['name','song_info']]
relation_df

                                    name  song_info
0                      선베드에 누워서 파도소리와 함께          0
1                      선베드에 누워서 파도소리와 함께      21158
2                      선베드에 누워서 파도소리와 함께      25730
3                      선베드에 누워서 파도소리와 함께          1
4                      선베드에 누워서 파도소리와 함께          2
...                                  ...        ...
125164  위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용      66048
125165  위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용      66049
125166  위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용      66050
125167  위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용      66051
125168  위아이가 새로운 컨셉으로 돌아왔어요~!! 많이 들어봐주세용      66052

[125169 rows x 2 columns]

In [160]:
relation_df.to_csv('relation_table.csv', encoding = 'utf-8-sig')